### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by brunoocasali** [brunoocasali/qke#4]
Add Wercker as C.I.

**Comment by babhishek21** [comment]
Hello! I want to do this. I was wondering how I should go about it? 
Would making a fork, adding CI to that and then PRing the changes back here work?

**Comment by brunoocasali** [comment]
@babhishek21 Sorry man, I don't know why we can do that without permissions, but now I've setup the Wercker + CodeClimate, and we have some issues with rubocop and test coverage, please send PR's to it! :D
