### ISSUE TITLE
Setup the code quality up to GPA 4.0

### ISSUE THREAD

**Issue by brunoocasali** [brunoocasali/qke#5]
Code Climate rulez

**Comment by 0sc** [comment]
Hey, I'd like to work on this. Is it still up for grabs?

**Comment by brunoocasali** [comment]
Of course! I will add CodeClimate, and then you can upgrade the code to best as you can! *(i will generate another issue to this :dancer: )

**Comment by brunoocasali** [comment]
Hey, I've added CodeClimate and Wercker, now just work to improve test coverage :dancer: (see the other issues)

**Comment by 0sc** [comment]
Are you treating [updating test coverage](https://github.com/brunoocasali/quake_log_parser/issues/1) and fixing codeclimate issues as different issues or as the same issue?

**Comment by brunoocasali** [comment]
@andela-ooranagwa No more! Now I've created one issue to solve all issues you can (#7). Or If you want to work with tests, you can do the (#1). And of course, you can suggest any change or issues I'll count to hacktoberfest!
